spring.application.name=practice

server.port=8085


spring.datasource.url=jdbc:mysql://springboot-mysql-dev.cbagccugwlb3.ap-south-1.rds.amazonaws.com:3306/testdb
spring.datasource.username=admin
spring.datasource.password=Magnas99
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver